# Generated by Django 4.1.3 on 2023-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=250),
        ),
    ]
