# Generated by Django 4.1.3 on 2023-01-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.TextField(),
        ),
    ]
