# Generated by Django 4.1.3 on 2023-01-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_alter_question_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
