# Generated by Django 4.1.3 on 2023-01-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='./'),
        ),
    ]
