# Generated by Django 4.1.3 on 2023-01-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0007_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/shrek.jpeg', upload_to=''),
        ),
    ]
