# Generated by Django 4.1.3 on 2023-01-24 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.TimeField(default=datetime.time(3, 28, 2, 662327)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='shrek.jpeg', upload_to=''),
        ),
    ]
