# Generated by Django 4.1.3 on 2023-01-24 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0009_question_time_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(default=datetime.time(15, 24, 8, 315017)),
        ),
    ]
